CREATE TABLE dbo.Selo
(    
    Id               INT             NOT NULL CONSTRAINT PK_IdSelo PRIMARY KEY,
    Descricao        VARCHAR(250)    NOT NULL
)

ALTER TABLE Jogo ADD Descricao VARCHAR(MAX) NOT NULL DEFAULT 'Melhor jogo';
ALTER TABLE Jogo ADD Imagem VARCHAR(MAX)
ALTER TABLE Jogo ADD Video VARCHAR(MAX)

INSERT INTO Selo (Id, Descricao) VALUES (1, 'OURO');
INSERT INTO Selo (Id, Descricao) VALUES (2, 'PRATA');
INSERT INTO Selo (Id, Descricao) VALUES (3, 'BRONZE');

ALTER TABLE Jogo ADD IdSelo INT NOT NULL DEFAULT 1 CONSTRAINT FK_IdSelo FOREIGN KEY REFERENCES Selo(Id);