UPDATE Jogo SET Descricao = 'SEM DESCRIÇÃO'
ALTER TABLE Jogo ADD Descricao VARCHAR(MAX) NOT NULL;
ALTER TABLE Jogo ADD Imagem VARCHAR(MAX)
ALTER TABLE Jogo ADD Video VARCHAR(MAX)

ALTER TABLE Jogo ADD IdSelo INT NOT NULL DEFAULT 1 CONSTRAINT FK_IdSelo FOREIGN KEY REFERENCES Selo(Id);